### ISSUE TITLE
How to NSData to String using iconv convert

### ISSUE THREAD

**Issue by yunchiri** [MaddTheSane/SwiftIconV#1]
I want example 
-->    nsdata -> nsstring('euc-kr')

when
let convertedString = NSString(data: NSData, encoding: 'EUC-KR')

> > ERROR!

then I will using like ( just sample)
let convertedString = NSString.Iconv(data: NSData, encoding: 'EUC-KR') 

> > Succes

could you show me 

how to convert to nsdata to string code?

Thanks sorry english

**Comment by MaddTheSane** [comment]
```
let data = NSData(...)
let converted = try? IconV.convertCString(UnsafePointer<Int8>(data.bytes), length: data.length, fromEncodingNamed: "EUC-KR")
```

The code doesn't use any Foundation classes because I wanted it to be usable with Linux.

**Comment by yunchiri** [comment]
Oops Thanks!!
